spring:
  datasource:
    url: jdbc:mariadb://${DATABASE_HOST}:${MARIA_DATABASE_PORT}/${MARIA_DATABASE_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

jwt:
  secret-key: ${JWT_SECRET_KEY}

logging:
  level:
    beyond.momentours: DEBUG
    org.springframework.security: TRACE
    org.mybatis: DEBUG
    java.sql: DEBUG